### Variables
@baseUrl = https://p7b5t9lqm5.execute-api.us-east-1.amazonaws.com/z004n87a
@apiKey = Test KEY


###
### Create VPC
POST {{baseUrl}}/vpcs
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "cidr_block": "10.1.0.0/16",
  "vpc_name": "simple-vpc",
  "subnets": [
    {
      "cidr_block": "10.1.1.0/24",
      "name": "subnet-1"
    }
  ]
}

###
### List All VPCs
GET {{baseUrl}}/vpcs
x-api-key: {{apiKey}}


###
### Get Specific VPC (replace with actual VPC ID)
GET {{baseUrl}}/vpcs/vpc-07b78c761cb0366d4
x-api-key: {{apiKey}}

